apiVersion: rbac.istio.io/v1alpha1
kind: RbacConfig
metadata:
  name: default
  namespace: istio-system
spec:
  mode: ON_WITH_INCLUSION
  inclusion:
    services:
      - fruits-api-service.micro-shake-factory.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: fruits-api-viewer
  namespace: micro-shake-factory
spec:
  rules:
    - services:
        - fruits-api-service.micro-shake-factory.svc.cluster.local
      methods:
        - GET
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: fruits-api-viewer-binding
  namespace: micro-shake-factory
spec:
  subjects:
    - properties:
        request.auth.claims[role]: "learner"
  roleRef:
    kind: ServiceRole
    name: fruits-api-viewer
