apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: throttle-handler
  namespace: istio-system
spec:
  compiledAdapter: memquota
  params:
    quotas:
      - name: request-quota-instance.instance.istio-system
        maxAmount: 500
        validDuration: 1s
        overrides:
          - dimensions:
              destination: fruits-api-service
            maxAmount: 1
            validDuration: 5s
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: request-quota-instance
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      destination: destination.service.name | unknown
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota-rule
  namespace: istio-system
spec:
  match: match(request.headers["user-agent"], "curl*")
  actions:
    - handler: throttle-handler
      instances:
        - request-quota-instance
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
    - quotas:
        - charge: 1
          quota: request-quota-instance
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: micro-shake-factory
spec:
  quotaSpecs:
    - name: request-count
      namespace: istio-system
  services:
    - name: fruits-api-service
      namespace: micro-shake-factory
